server:
  port: 8090


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/lz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
      data-format: yyyy-MM-dd HH:mm:ss
      servlet:
        mulipart:
          max-file-size: 500MB
          max-request-size: 500MB
        jackson:
          time-zone: GMT+8
          data-format: yyyy-MM-dd HH:mm:ss



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  #type-aliases-package: com.com.springcloud.entities
configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
