server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/lz?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username:  root
    password:  root
 mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # redis
 # redis:
 #   database: 9
 #   host: 41.5.252.223
 #   port: 6379
 #   password: zyghyfb
 # timeout: 3000
    # password:
 # pool:
 #   minIdle: 0
 #   maxIdle: 10
 #   maxWait: -1ms
 #   maxActive: 100
#    timeout: 1000ms
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8090
configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



#    # Redis数据库索引
#    spring:redis.database=9
#    # Redis服务器地址
#    spring.redis.host=41.5.252.223
#    # Redis服务器连接端口
#    spring.redis.port=6379
#    # Redis服务器连接密码（默认为空）
#    spring.redis.password=zyghyfb
#    # 连接超时时间（毫秒）
#    spring.redis.timeout=3000
#    # 连接池最大连接数（使用负值表示没有限制）
#    spring.redis.lettuce.pool.max-active=100
#    spring.redis.lettuce.pool.min-idle=0
#    spring.redis.lettuce.pool.max-idle=10
#    spring.redis.lettuce.pool.max-wait=-1ms
#    spring.redis.lettuce.shutdown-timeout=1000ms
